apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: qr-scanner-app

resources:
  - namespace.yaml
  - backend-deployment.yaml
  - backend-service.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - ingress.yaml

images:
  - name: backend
    newName: ghcr.io/your-username/your-repo-name-backend
    newTag: latest
  - name: frontend
    newName: ghcr.io/your-username/your-repo-name-frontend
    newTag: latest