apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: qr-scanner-app
  labels:
    app: qr-scanner-app
    environment: base
type: Opaque
data:
  secret-key: "cHJvZC1zdXBlci1zZWNyZXQta2V5LTEyMw=="  # base64 encoded "prod-super-secret-key-123"
  session-secret: "c2Vzc2lvbi1zZWNyZXQta2V5LWZvci1wcm9k"  # base64 encoded "session-secret-key-for-prod"
  admin-password: "cHJvZC1hZG1pbi1wYXNzd29yZA=="  # base64 encoded "prod-admin-password"