apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: qr-scanner-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/mdazamdevops/qr-scanner-kubernetes-argocd.git
    targetRevision: HEAD
    path: kubernetes/base
  destination:
    server: https://kubernetes.default.svc
    namespace: qr-scanner-app
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true