apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: qr-scanner-app
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        environment: production
        version: v1.0.0
    spec:
      containers:
      - name: backend
        env:
        - name: ENVIRONMENT
          value: "production"
        - name: LOG_LEVEL
          value: "info"
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 45
          periodSeconds: 15
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
      nodeSelector:
        node-type: worker
      tolerations:
      - key: "dedicated"
        operator: "Equal"
        value: "qr-scanner"
        effect: "NoSchedule"